- name: Install common tools on Redhat
  dnf:
    name:
      - curl
      - wget
      - htop
      - pass
      - jq
      - unzip
      - git
      - git-gui
      - gpg
      - qbittorrent
  when: "ansible_os_family == 'RedHat'"
  become: yes

- name: Install common tools on Archlinux
  pacman:
    name:
      - curl
      - wget
      - htop
      - pass
      - jq
      - unzip
      - git
      - tk
      - qbittorrent
      - vlc
      - steam
  when: "ansible_os_family == 'Archlinux'"
  become: yes

- name: Register repolist
  shell: dnf repolist enabled | grep -c rpmfusion; true
  register: repolist
  when: "ansible_os_family == 'RedHat'"

- name: Register fedora version
  shell: rpm -E %fedora
  register: fedoraversion
  when: "ansible_os_family == 'RedHat' and repolist.stdout == '0'"

- name: Enable RPMFusion
  shell: "dnf install -y --refresh https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedoraversion.stdout }}.noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedoraversion.stdout }}.noarch.rpm"
  become: yes
  when: "ansible_os_family == 'RedHat' and repolist.stdout == '0'"
  register: output

- name: Install Accelerated video decoding packages
  dnf:
    name:
      - libva
      - libva-utils
  when: "ansible_os_family == 'RedHat'"
  become: yes

- name: Install multimedia
  dnf:
    name:
      - '@multimedia'
      - '@sound-and-video'
  become: yes
  when: "ansible_os_family == 'RedHat'"

- name: Import repository key
  rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
  become: yes
  when: "ansible_os_family == 'RedHat'"

- name: Add yum repository for 1password
  yum_repository:
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    name: 1password
    description: 1Password Stable Channel
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
  become: yes
  when: "ansible_os_family == 'RedHat'"

- name: Install 1password on RedHat
  dnf:
    name: 1password
    enablerepo: 1password
  become: yes
  when: "ansible_os_family == 'RedHat'"

- name: Register 1Password GPG key presence
  shell: gpg -k | grep -c 1Password; true
  register: gpgkey

- name: Add 1password GPG key
  shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import
  when: "ansible_os_family == 'Archlinux' and gpgkey.stdout == '0'"

- name: Install 1password on Archlinux
  kewlfft.aur.aur:
    name:
      - 1password
  when: "ansible_os_family == 'Archlinux'"

- name: Install postman on Archlinux
  kewlfft.aur.aur:
    name:
      - postman-bin
  when: "ansible_os_family == 'Archlinux'"
