- name: Install fzf and silver-searcher on Redhat
  dnf:
    name:
      - fzf
      - the_silver_searcher
  become: yes
  when: "ansible_os_family == 'RedHat'"

- name: Install fzf and silver-searcher on Archlinux
  pacman:
    name: 
      - fzf
      - the_silver_searcher
  become: yes
  when: "ansible_os_family == 'Archlinux'"

