FROM ubuntu:focal

RUN apt-get update && apt-get -y install sudo
RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

WORKDIR /home/docker/workspace/dotfiles
COPY . .

USER docker

CMD /bin/bash
