- name: Install Fish on Redhat
  dnf:
    name: fish
  when: "ansible_os_family == 'RedHat'"
  become: yes

- name: Install Fish on Archlinux
  pacman:
    name: [ fish, thefuck ]
  when: "ansible_os_family == 'Archlinux'"
  become: yes

- name: Change shell to fish
  user:
    name: "{{ current_user }}"
    shell: /usr/bin/fish
  become: yes

- name: Ensure fish config directory exists
  file:
    path: ~/.config/fish/
    state: directory

- name: Link Fish config
  file:
    src: ~/Workspace/dotfiles/config.fish
    dest: ~/.config/fish/config.fish
    state: link

- name: Ensure Functions directory does not exist
  file:
    path: ~/.config/fish/functions
    state: absent

- name: Link Fish functions
  file:
    src: ~/Workspace/dotfiles/fish_functions/
    dest: ~/.config/fish/functions
    state: link
